### PR TITLE
Include docs in package

### PR DESCRIPTION
**Pull request by jodal**

### CODE REVIEW

**Comment by jodal** [comment]
[check-manifest](https://pypi.python.org/pypi/check-manifest) is a nice tool to test if your `MANIFEST.in` is complete.

**Comment by tkem** [comment]
Thanks. Will look into that.

**Comment by jodal** [comment]
My motivation for this is that Debian prefers to build packages from PyPI releases and not GitHub tag tarballs. For the Debian package to include docs, we then need the PyPI package to include docs.

**Comment by tkem** [comment]
Yes, yes, I get it ;-)
Will look into it tomorrow, promise. Was busy with various MoMo releases ;-)

**Comment by jodal** [comment]
The current uritools release is packaged from a GitHub tag tarball, so I'm happy as long as this is fixed before the next release :-)

**Comment by tkem** [comment]
Will also release a v1.0.2 then ASAP.

**Comment by tkem** [comment]
Will also have to tell travis to use "coverage<4", since I guess that's what breaks the build for Python 3.2...

**Comment by jodal** [comment]
I think it's fair game to just drop support for Python 3.2 at this point.

**Comment by tkem** [comment]
Well, I disagree. `uritools` itself works fine on Python 3.2, and until I feel I really *need* some features  from >3.2, I'll keep it that way. Would much rather drop support for Python 2.7, but there are some packages out there that depend on `uritools` that still haven't migrated to Python 3 ;-)

**Pull request merged**
